const EXPRESS_COOKIE_SECRET = process.env.EXPRESS_COOKIE_SECRET || 'HawUCRwWol68ZvUvmUUH'
const EXPRESS_COOKIE_NAME = process.env.EXPRESS_COOKIE_NAME || 'connect.sid'
const EXPRESS_COOKIE_DOMAIN = process.env.EXPRESS_COOKIE_DOMAIN
const ADMIN_COOKIE_SECRET = process.env.ADMIN_COOKIE_SECRET || EXPRESS_COOKIE_SECRET
const ADMIN_COOKIE_NAME = process.env.ADMIN_COOKIE_NAME || 'adminbro'

export default {
  EXPRESS_COOKIE_SECRET,
  EXPRESS_COOKIE_NAME,
  EXPRESS_COOKIE_DOMAIN,
  ADMIN_COOKIE_SECRET,
  ADMIN_COOKIE_NAME,
}
